spring:
    application:
        name: sutt
    boot:
        admin:
            client:
                url: http://localhost:8080
    # datasource:
    #     url: jdbc:postgresql://localhost:5432/mydatabase
    #     username: myuser
    #     password: secret
    sql:
        init:
            mode: always 
    flyway:
        enabled: true

management:
    endpoint:
        shutdown:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true